### ISSUE TITLE
start Quizu po wyborze trybu z hamburger menu

### ISSUE THREAD

**Issue by MichalCzajkowski1000** [dmgawel/coderscamp2021-project-1#70]
po wyborze z hamburger-menu trybu quizu, quiz uruchamia się i licznik odmierzający czas na pytanie od razu zaczyna odliczać. Użytkownik tego nie dostrzeże dopóki nie zamknie hamburgera :(

**Comment by dmgawel** [comment]
Słusznie, w logice hamburgera trzeba dodać zamykanie hamburgera po kliknięciu w element menu
